server:
  port: 8080
  servlet:
    context-path: /api
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

spring:
  application:
    name: simple-api
  profiles:
    active: local

# MyBatis Plus 配置
mybatis-plus:
  # 多包名使用 例如 com.example.simple.modules.**.mapper,com.example.vv.modules.**.mapper
  mapperPackage: com.example.simple.modules.**.mapper
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      # 逻辑删除配置（如果需要可以打开，保持简单暂时不用）
      # logic-delete-field: is_deleted # 全局逻辑删除的实体字段名
      # logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      # logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      # 主键策略 AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      id-type: ASSIGN_UUID

logging:
  config: classpath:logback-spring.xml

auth:
  single-session:
    # true:开启后，新登录会使旧设备Token失效; false:允许多设备同时登录
    enabled: true