# ===================================================================
#                  测试服务器环境 (Test Profile)
# ===================================================================
spring:
  config:
    activate:
      on-profile: test
  datasource:
    lazy-initialization: false
    url: jdbc:mysql://localhost:3306/simple_api_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: SimpleHikariPool-Test
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20

server:
  port: 8082

file:
  root-path: "/www/wwwroot/java/simple/uploads/"

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  javadoc:
    enabled: true