# ===================================================================
#                  生产环境 (Production Profile)
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    lazy-initialization: false
    # TODO: 替换为生产环境数据库的JDBC URL
    url: "jdbc:mysql://<your-production-db-host>:3306/simple_api_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    # TODO: 替换为生产环境数据库的用户名
    username: "<your-production-db-user>"
    # TODO: 替换为生产环境数据库的密码
    password: "<your-production-db-password>"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: SimpleHikariPool-Prod
      # 初始化连接的超时时间 (30秒)
      connection-timeout: 30000
      # 生产环境建议维持少量热连接以提高性能
      minimum-idle: 10
      # 根据生产服务器规格和预期并发量调整
      maximum-pool-size: 50

server:
  error:
    # 不在响应中暴露堆栈信息，增强安全性
    include-stacktrace: never

# Mybatis-plus: 生产环境关闭 SQL 打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# Logging: 生产环境使用 INFO 级别
logging:
  level:
    root: INFO
    com.example.simple: INFO

file:
  root-path: "/path/to/your/production/uploads/"

# SpringDoc: 生产环境禁用 Swagger
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
  javadoc:
    enabled: false

# Actuator 监控配置
management:
  endpoints:
    web:
      exposure:
        # 生产环境默认只暴露最核心的 health 端点，用于负载均衡器的健康检查
        include: "health"