# ===================================================================
#                  测试环境 (Testing Profile)
# ===================================================================

server:
  port: 8082
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/simple_api_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: SimpleHikariPool-Test
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20

# Mybatis-plus 开发环境开启 SQL 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.simple: DEBUG

file:
  upload-path: /www/wwwroot/java/simple/uploads/
  # 外部访问上传图片的URL前缀
  access-url-prefix: /uploads/

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  javadoc:
    enabled: true