# ===================================================================
#               本地开发环境 (Local Profile)
# ===================================================================
spring:
  config:
    activate:
      on-profile: local
  datasource:
    lazy-initialization: false
    url: jdbc:mysql://localhost:3306/simple_api_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: SimpleHikariPool-Local
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20

# Mybatis-plus: 开发环境开启 SQL 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Logging: 开发环境使用 DEBUG 级别
logging:
  level:
    com.example.simple: DEBUG

# SpringDoc: 开发环境启用 Swagger
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  javadoc:
    enabled: true

# Actuator 监控配置
management:
  endpoints:
    web:
      exposure:
        # 开发时可以暴露所有端点，方便调试
        include: "*"