# ===================================================================
#               主配置文件 (所有环境共享的默认配置)
# ===================================================================
app:
  cache:
    # 缓存总开关。设置为 false 可以完全禁用缓存功能，应用将回退到直接访问数据库。
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /api
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

spring:
  application:
    name: simple-api
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0

# MyBatis Plus 全局配置
mybatis-plus:
  mapperPackage: com.example.simple.modules.**.mapper
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      # 逻辑删除配置
      # logic-delete-field: is_deleted # 全局逻辑删除的实体字段名
      # logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      # logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      # 主键策略 AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      id-type: ASSIGN_UUID

# 日志配置
logging:
  config: classpath:logback-spring.xml

# 认证配置
auth:
  single-session:
    # true:开启后，新登录会使旧设备Token失效; false:允许多设备同时登录
    enabled: true

file:
  storage:
    type: local
  # 默认的、可移植的文件存储根路径
  root-path: "#{systemProperties['user.dir']}/uploads"
  # 默认的URL访问前缀
  access-url-prefix: /uploads/
  # 云存储服务商配置模板
  provider:
    aliyun-oss:
      endpoint:
      access-key-id:
      access-key-secret:
      bucket-name:
    tencent-cos:
      region:
      secret-id:
      secret-key:
      bucket-name:
    huawei-obs:
      endpoint:
      access-key-id:
      access-key-secret:
      bucket-name:

# Actuator 监控配置
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        # 暴露 health 和 info 两个端点
        # health: 显示应用健康状况
        # info: 显示应用基本信息
        include: health, info
  endpoint:
    health:
      # 总是显示详细的健康信息，包括数据库、Redis等组件的状态
      show-details: always
  # (可选，但推荐) 为 Actuator 端点设置一个独立的端口，增强安全性
  # server:
  #   port: 8081