# ===================================================================
#                  正式/生产环境 (Production Profile)
# ===================================================================

spring:
  config:
    activate:
      on-profile: prod

server:
  error:
    include-stacktrace: never

# Mybatis-plus 日志配置 (生产环境关闭 SQL 打印以提高性能)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# 日志级别配置 (生产环境通常设置为 INFO 或 WARN)
logging:
  level:
    root: INFO
    com.example.simple: INFO

file:
  access-url-prefix: /uploads/

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
  javadoc:
    enabled: false